release/action.yaml
This is needed to publish packages.
**Changes**
* fix(release): pass npm auth token to semantic release
=> fix(release): pass npm auth token to semantic release

lint/action.yaml
It seems reviewdog's level param is counterintuitive and it refers to the behavior we want for the action when there are annotations (i.e. when there are either errors, warnings or notices).
Since we currently don't pass a level param to reviewdog, it is picking the default, which is `error`: https://github.com/reviewdog/action-eslint/blob/master/action.yml#L12
From reviewdog's source code, it seems as soon as there are annotations (https://github.com/reviewdog/reviewdog/blob/master/doghouse/server/doghouse.go#L101) from the lint output, then when calling `conclusion` we can see that it will `failure` if the level is `error` and `neutral` for `info` and `warning`
This PR aims to test if by passing `warning` as `level` we can avoid failures of our actions for warnings, which are prominent …
=> feat: allow configuring level for reviewdog

lint/README.md, lint/action.yaml
Hopefully having level as "warning" and adding fail-on-error to "true" makes this work as we expected (report all warnings and errors but only fail if it is an error)
Follow up of: https://github.com/open-turo/actions-node/pull/10
=> fix: add fail-on-error param (to combine w/ level)

lint/action.yaml
Have we considered trying this other reporter?
Seems nicer as it actually creates reviews and comments, and also seems to be the default currently.
Maybe there is a reason I'm missing for using the `github-check` instead, so creating this PR for discussion.
Link to the docs: https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review
=> feat: try github-pr-review instead of github-check

release/action.yaml
We could be more flexible and not make this a breaking change, but since we are moving to Node 16 (if we haven't already everywhere else) I think it's ok to just assume Node 16 is the minimum.
**Changes**
* feat: update semantic release action to v3
=> feat: update semantic release action to v3

release/action.yaml
I wasn't able to see the output in a consumer so I had a look and we're missing an id for proper forwarding.
**Changes**
* fix: adds missing id so step outputs are forwarded
=> fix: adds missing id so step outputs are forwarded

release/action.yaml
This changes originates from https://github.com/semantic-release/git/issues/196. Trying to get to use semantic-release/git in combination with this action. In order for this to work, we have to be able to get semantic release to use the passed `GITHUB_TOKEN` instead of the default git configured
**Changes**
* fix(release): don't persist credentials when checking out the repo
=> fix(release): don't persist credentials when checking out the repo

release/action.yaml
The check is not needed, as when executed `checkout-repo` will always be true
**Changes**
* fix(release): remove not needed if for force-depth
=> fix(release): remove not needed if for force-depth

lint/action.yaml, release/action.yaml, test/action.yaml
Repositories in open-turo use npm instead of yarn by default. This PR adds support to use npm in all the actions when there is no `yarn.lock` file in the repo.
Not sure if there is a nicer way to distinguish between yarn and npm in the action
**Changes**
* feat: use npm instead of yarn when there is no yarn.lock
=> feat: use npm instead of yarn when there is no yarn.lock

lint/README.md, lint/action.yaml, release/README.md, release/action.yaml, test/README.md, test/action.yaml
NPM by default uses the `NPM_TOKEN` env var to authenticate against npmjs.org. This PR adds support to specify this token in all the actions via the `npm-token` input.
It also keeps the `npm-auth-token` (updating the docs a bit), so we can still authenticate to at least one private registry by configuring a npmrc file.
**Changes**
* feat: add support to specify npm-token
=> feat: add support to specify npm-token

lint/README.md, lint/action.yaml, lint/scripts/beta-check.sh
It would be good practice to warn/alert developers working in consumer packages that they are consuming a beta-release of a certain package, because ideally we wouldon’t really want to merge such a change, and would need to publish and consume a proper release first.
**Changes**
* feat: add step to check for beta releases
=> feat: add step to check for beta releases

release/action.yaml
This updates the extra-plugins to default to `@open-turo/semantic-release-config@^1.4.0`.  This will allow us to stop needing to configure it everywhere.
=> fix(release): default extra-plugins to open-turo/semantic-release-config

docs/breaking-changes/v4.md, lint/README.md, lint/action.yaml
This allows the user to pass a custom script that they would have defined in package.json, that would run in CI, instead of only running eslint. This gives the user flexibility to run any other lint checks they might want, like type-checking etc.
Fixes [#CP-954](https://team-turo.atlassian.net//browse/CP-954)
**Changes**
* feat: run custom lint script instead of just eslint
=> CP-954: Run custom lint script instead of just eslint

lint/action.yaml
Running pre-commit is a definitely good practice, but not using pre-commit (if a consumer uses husky + lint-staged for example) shouldn't be a blocker to using this action
=> fix(lint): run pre-commit step if .pre-commit-config exists

.github/workflows/ci.yaml, .github/workflows/release.yaml, release/action.yaml
instead of cycjimmy/semantic-release-action in order to support higher versions of semantic-release and node
=> feat(release): use open-turo/actions-release/semantic-release

lint/action.yaml, release/action.yaml, test/action.yaml
Bools are not properly being evaluated by GHA
=> Modify conditional checkout commands

.pre-commit-config.yaml, lint/README.md, lint/action.yaml, release/README.md, script/update-action-readme, test/README.md
Run open-turo/actions-release/lint-release notes if the event is a pull_request
Also add action-docs pre-commit hook to generate documentation
**Changes**
* feat: run lint release notes as part of lint
* build: use action-docs to generate readmes
* docs: update actions readme
=> feat: run lint release notes as part of lint

build-docker/README.md, build-docker/action.yaml, build/README.md, build/action.yaml, lint/README.md, prerelease/README.md, prerelease/action.yaml, release/README.md, release/action.yaml, test/README.md
This PR adds 3 new actions:
* `build-docker` - Build a docker image for the project
* `build` - Run the `build` NPM script in a project - this was being done as part of release, but now we need it for prerelease too 
* `prerelease` - Trigger a release from a PR when the prerelease label is there (optionally building a docker image)
Now `release` also optionally builds docker images
This is inspired by `actions-jvm` and follows the same idea of having a local `.docker-config` file for the docker image name
**Changes**
* feat: add a build-docker action
* feat: add a build action
* refactor(release): use internal build action
* feat(release): build docker as part of release
* docs: update actions readme to rely on action docs even more
* feat: add prerelease action
* chore: …
=> Add support for pre-release

release/action.yaml
We are missing the `inputs.` prefix when checking if we should build a docker image
**Changes**
* fix(release): use correct refs for dockerhub inputs
=> fix(release): use correct refs for dockerhub inputs

release/action.yaml
In repositories where we have many many branches semantic release takes a long time to run when using https://github.com/open-turo/semantic-release-config. This change updates the release action so it can only be triggered on the repository default branch or in PR branches.
This should speed things up in those repositories.
This also creates the side effect that we will only allow releases from PRs or the repository default branch, which works for our use cases (if needed we could always add inputs to use different branches or try to reconcile things with any releaserc file that is there locally, but all that is future work).
**Changes**
* fix(release): only support releases from default branches or PRs
=> fix(release): only support releases from default branches or PRs

release/action.yaml
Currently, running `release` when there are no commits to release, causes an error because docker-build is triggered unintentionally.
**Changes**
* fix: ensures docker build is not executed without a release number
=> fix: ensures docker build is not executed without a release number

lint/action.yaml
NPM libs require the NPM token to be present when running semantic-release
**Changes**
* fix(lint): pass npm tokens to lint-release-notes
=> fix(lint): pass npm tokens to lint-release-notes

lint/action.yaml
The OSS action we use for file existence was designed to check for "all" files rather than "any" file in a list, we hack our way around this for now by using a glob pattern which captures any file extension, since the file we are after has a pretty unique name
Fixes [#CP-1283](https://team-turo.atlassian.net//browse/CP-1283)
**Changes**
* fix: use glob pattern to capture different pre-commit file extensions
=> fix(lint): use glob pattern to capture different pre-commit file extensions

build-docker/README.md, build/README.md, build/action.yaml, lint/README.md, lint/action.yaml, prerelease/README.md, prerelease/action.yaml, release/README.md, release/action.yaml, script/update-action-readme, test/action.yaml
action-docs were failing and this PR also updates action-setup-tools (couldn't figure out why renovate wasn't picking this update)
**Changes**
* ci: pin action-docs version and update readme for it to work
* docs: generate docs
* build(deps): use actions-setup-tools@v2
=> ci: pin action-docs version and update readme for it to work

install-dependencies/action.yaml
In https://github.com/open-turo/actions-node/pull/66 a bug was introduce where we forgot to pass `persist-credentials: false` to the Checkout step. 
* fix: add back persist-credentials
=> CP: Add back persist-credentials to checkout step in install-dependencies

.github/workflows/ci.yaml, lint/action.yaml
not sure why renovatebot is not picking it. The previous version results in installing an older version of node 
**Changes**
* fix: update action-pre-commit
=> fix: update action-pre-commit

lint/action.yaml, prerelease/action.yaml, release/action.yaml
Update `actions-release` to the latest version. It requires semantic-release 23 (noop on this repo).
I don't think this should be a breaking change in this action, but we could go that way to be extra cautious. Maybe the tests in the TODOs are enough for this.
Not sure why renovatebot is not picking these updates.
Everything is working fine 🎉 
**TODOs**
**Changes**
* fix: update actions-release to v5
=> fix: update actions-release to v5

install-dependencies/action.yaml, lint/action.yaml
This PR updates this repo to be able to cache pre-commit hooks in S3. It depends on https://github.com/open-turo/action-pre-commit/pull/101
Apart from that removes an extra call to actions-cache, which is not needed since the action already has a post run logic to write the cache back to S3.
**Changes**
* feat: cache pre-commit in s3
* fix(install-dependencies): remove extra cache run
=> feat: cache pre-commit in s3

prerelease/action.yaml
This PR updates the `prerelease` action so it uses the existing https://github.com/open-turo/action-conditional-pr-comment action, which simplifies the code a little bit and removes the need to directly maintain some external actions.
**Changes**
* fix(prerelease): use open-turo/action-conditional-pr-comment
=> fix(prerelease): use open-turo/action-conditional-pr-comment

prerelease/action.yaml
When updating the comment action, I used the wrong value for github-token.
**Changes**
* fix(prerelease): use correct value for github-token
=> fix(prerelease): use correct value for github-token

prerelease/action.yaml
We are double-wrapping the text-detector in comment format. This fixes it by removing the comment wrappers from the text-detector.
**Changes**
* fix: avoid double-wrapping text-detector in a comment
=> fix: avoid double-wrapping text-detector in a comment

.pre-commit-config.yaml, test/action.yaml
For some reason renovatebot is not picking this one. Updating it manually
**Changes**
* fix(test): use actions-node@v7
* ci: update pre-commit config
=> fix(test): use actions-node@v7
